"""Add last_service_date to vehicles table

Revision ID: 3f13eea9d886
Revises: 70ecd0b38d21
Create Date: 2026-08-04 22:27:00.376272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f13eea9d886'
down_revision = '70ecd0b38d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_service_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('last_service_date')

    # ### end Alembic commands ###
