"""Move collector_code to CollectorProfile

Revision ID: 54b9ab3b1822
Revises: e83f74d8e17c
Create Date: 2026-07-29 23:20:34.578535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b9ab3b1822'
down_revision = 'e83f74d8e17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_code', sa.String(length=25), nullable=True))
        batch_op.create_index(batch_op.f('ix_collector_profiles_collector_code'), ['collector_code'], unique=True)

    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_collector_code'))
        batch_op.create_index(batch_op.f('ix_pickup_requests_collector_id'), ['collector_id'], unique=False)
        batch_op.create_foreign_key('fk_pickups_collector', 'users', ['collector_id'], ['id'])
        batch_op.drop_column('collector_code')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vehicles_collector_code_key'), type_='unique')
        batch_op.drop_column('collector_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('vehicles_collector_code_key'), ['collector_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_code', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pickup_requests_collector_id'))
        batch_op.create_index(batch_op.f('ix_pickup_requests_collector_code'), ['collector_code'], unique=True)
        batch_op.drop_column('collector_id')

    with op.batch_alter_table('collector_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collector_profiles_collector_code'))
        batch_op.drop_column('collector_code')

    # ### end Alembic commands ###
