"""Remove collector identification number

Revision ID: 70ecd0b38d21
Revises: 54b9ab3b1822
Create Date: 2026-07-30 23:07:18.185343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ecd0b38d21'
down_revision = '54b9ab3b1822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collector_profiles_identification_number'), type_='unique')
        batch_op.drop_column('identification_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_collector_profiles_identification_number'), ['identification_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
