"""add collector code

Revision ID: a332842cfaa6
Revises: 7ba0a6d6eaa7
Create Date: 2026-07-29 21:11:24.764208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a332842cfaa6'
down_revision = '7ba0a6d6eaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_code', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_collector_code'), ['collector_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_collector_code'))
        batch_op.drop_column('collector_code')

    # ### end Alembic commands ###
