"""Add collector_id

Revision ID: e83f74d8e17c
Revises: a332842cfaa6
Create Date: 2026-07-29 22:38:13.511036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83f74d8e17c'
down_revision = 'a332842cfaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_code', sa.String(length=25), nullable=True))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_collector_id'))
        batch_op.create_index(batch_op.f('ix_pickup_requests_collector_code'), ['collector_code'], unique=True)
        batch_op.drop_constraint(batch_op.f('pickup_requests_collector_id_fkey'), type_='foreignkey')
        batch_op.drop_column('collector_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_collector_code'))
        batch_op.create_unique_constraint(None, ['collector_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_vehicles_collector_code'), ['collector_code'], unique=True)

    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('pickup_requests_collector_id_fkey'), 'users', ['collector_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pickup_requests_collector_code'))
        batch_op.create_index(batch_op.f('ix_pickup_requests_collector_id'), ['collector_id'], unique=False)
        batch_op.drop_column('collector_code')

    # ### end Alembic commands ###
