"""add recycling batches

Revision ID: fb685c1896ef
Revises: 3f13eea9d886
Create Date: 2026-08-21 22:45:30.135281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb685c1896ef'
down_revision = '3f13eea9d886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycling_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('recycling_company_id', sa.Integer(), nullable=False),
    sa.Column('waste_category_id', sa.Integer(), nullable=False),
    sa.Column('weight_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_processed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], ),
    sa.ForeignKeyConstraint(['recycling_company_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recycling_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recycling_batches_pickup_id'), ['pickup_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_recycling_batches_recycling_company_id'), ['recycling_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycling_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycling_batches_waste_category_id'), ['waste_category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycling_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recycling_batches_waste_category_id'))
        batch_op.drop_index(batch_op.f('ix_recycling_batches_status'))
        batch_op.drop_index(batch_op.f('ix_recycling_batches_recycling_company_id'))
        batch_op.drop_index(batch_op.f('ix_recycling_batches_pickup_id'))

    op.drop_table('recycling_batches')
    # ### end Alembic commands ###
